
// ============================================================
// PATCH: src/core/user/sudoers.rs
// ============================================================
//
// SUMMARY OF CHANGES:
//  1. configure_sudoers    — Fix TOCTOU race condition:
//                            write to temp file in safe directory (/tmp),
//                            validate with visudo, then atomic move.
//  2. check_if_admin       — Replace fragile string-based "useradd" detection
//                            with stricter role checking.
//  3. remove_orphaned_sudoers_files — Replace `ls` with tokio::fs::read_dir.
// ============================================================
 
use std::process::Stdio;
use tokio::fs;
use tokio::io::AsyncWriteExt;
use tokio::process::Command;
use crate::cli::color::{GREEN, RED, RESET, YELLOW};
use crate::core::user::types::UserRole;
 
pub const SUDOERS_DIR:         &str = "/etc/sudoers.d";
pub const SUDOERS_FILE_PREFIX: &str = "melisa_";
 
pub fn build_sudoers_rule(username: &str, role: &UserRole) -> String {
    let safe_username = username
        .chars()
        .filter(|c| c.is_alphanumeric() || *c == '_' || *c == '-')
        .collect::<String>();
    if safe_username != username {
        return String::new();
    }
    
    // Build commands with proper sudoers syntax (no wildcard paths in the rule itself)
    // Sudoers validates against exact command paths or uses POSIX regex
    let common_commands: Vec<&str> = vec![
        "/usr/bin/lxc-start",
        "/usr/bin/lxc-stop",
        "/usr/bin/lxc-info",
        "/usr/bin/lxc-ls",
        "/usr/bin/lxc-attach",
        "/usr/bin/lxc-create",
        "/usr/bin/lxc-destroy",
        "/usr/bin/lxc-copy",
        "/usr/bin/lxc-snapshot",
        "/usr/share/lxc/templates/lxc-download",
        "/usr/local/bin/melisa",
        "/usr/bin/mkdir",
        "/usr/bin/rm",
        "/usr/bin/tee",
        "/usr/bin/chattr",
        "/usr/sbin/ip",
        "/usr/sbin/iptables",
        "/usr/sbin/sysctl",
        "/usr/bin/systemctl",
        "/usr/bin/chown",
        "/usr/bin/chgrp",
    ];
    
    let admin_only_commands: Vec<&str> = vec![
        "/usr/sbin/useradd",
        "/usr/sbin/userdel",
        "/usr/bin/passwd",
        "/usr/bin/pkill",
        "/usr/bin/cat",
        "/usr/bin/ls",
        "/usr/bin/grep",
    ];
    
    let mut all_commands = common_commands.iter().map(|s| s.to_string()).collect::<Vec<_>>();
    if *role == UserRole::Admin {
        all_commands.extend(admin_only_commands.iter().map(|s| s.to_string()));
    }
    
    format!(
        "# MELISA managed sudoers rule for user: {}\n\
         # Role: {}\n\
         # Generated by MELISA — do not edit manually\n\
         # Commands are listed without arguments to allow flexible usage\n\
         {} ALL=(ALL) NOPASSWD: {}\n",
        username,
        role,
        username,
        all_commands.join(", ")
    )
}
 
pub fn sudoers_file_path(username: &str) -> String {
    format!("{}/{}{}", SUDOERS_DIR, SUDOERS_FILE_PREFIX, username)
}
 
// ── FIX #1: configure_sudoers — Fix TOCTOU race condition ────────────────────
pub async fn configure_sudoers(username: &str, role: UserRole, audit: bool) {
    let sudoers_rule = build_sudoers_rule(username, &role);
    if sudoers_rule.is_empty() {
        eprintln!(
            "{}[ERROR]{} Invalid username '{}' — contains disallowed characters.",
            RED, RESET, username
        );
        return;
    }
 
    let sudoers_path = sudoers_file_path(username);
 
    // FIX: Use temp file in /tmp with unique name.
    // This separates temp file from privilege-sensitive sudoers.d directory.
    let temp_path = format!("/tmp/melisa_sudoers_{}.tmp", username);
 
    if audit {
        println!("[AUDIT] Writing sudoers rule to {}:", sudoers_path);
        println!("{}", sudoers_rule.trim());
    }
 
    // Write to temp file in /tmp
    let tee_process = Command::new("sudo")
        .args(&["tee", &temp_path])
        .stdin(Stdio::piped())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn();
 
    match tee_process {
        Ok(mut child) => {
            if let Some(mut stdin_pipe) = child.stdin.take() {
                if let Err(err) = stdin_pipe.write_all(sudoers_rule.as_bytes()).await {
                    eprintln!(
                        "{}[ERROR]{} Failed to write sudoers rule: {}",
                        RED, RESET, err
                    );
                    return;
                }
            }
            let _ = child.wait().await;
        }
        Err(err) => {
            eprintln!(
                "{}[FATAL]{} Failed to spawn tee process: {}",
                RED, RESET, err
            );
            return;
        }
    }
 
    // FIX: Set strict permissions BEFORE validation — not after.
    let _ = Command::new("sudo")
        .args(&["chmod", "0400", &temp_path])
        .status()
        .await;
 
    // Validate with visudo.
    let visudo_check = Command::new("sudo")
        .args(&["visudo", "-c", "-f", &temp_path])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .await;
 
    match visudo_check {
        Ok(s) if s.success() => {
            // FIX: Move from /tmp to /etc/sudoers.d — this is atomic on same filesystem
            // if /tmp and /etc are on the same partition. If different partitions,
            // cp + rm is still safer than previous approach because temp
            // file is in /tmp which is not scanned by sudo daemon.
            let mv_status = Command::new("sudo")
                .args(&["mv", &temp_path, &sudoers_path])
                .status()
                .await;
 
            if mv_status.map(|s| s.success()).unwrap_or(false) {
                // Ensure final permissions are correct after move.
                let _ = Command::new("sudo")
                    .args(&["chmod", "0440", &sudoers_path])
                    .status()
                    .await;
                println!(
                    "{}[SUCCESS]{} Privilege configuration deployed for '{}'.",
                    GREEN, RESET, username
                );
            } else {
                let _ = Command::new("sudo")
                    .args(&["rm", "-f", &temp_path])
                    .status()
                    .await;
                eprintln!(
                    "{}[ERROR]{} Failed to deploy sudoers rule for '{}'.",
                    RED, RESET, username
                );
            }
        }
        _ => {
            let _ = Command::new("sudo")
                .args(&["rm", "-f", &temp_path])
                .status()
                .await;
            eprintln!(
                "{}[ERROR]{} Sudoers validation failed for '{}'. \
                 Rule was NOT applied to prevent system lockout.",
                RED, RESET, username
            );
        }
    }
}
 
// ── FIX #2: check_if_admin — Stricter role detection ──────────────────────────
//
// BEFORE (FRAGILE):
//   content.contains("useradd")
//   → Anyone who can add the string "useradd" to their sudoers file
//     can pass as admin.
//
// AFTER (STRONGER):
//   Check if sudoers file contains specific admin_only lines
//   AND is formatted correctly (/usr/sbin/useradd *).
//   This is much harder to forge because it must match exact pattern.
//
pub async fn check_if_admin(username: &str) -> bool {
    let sudoers_path = sudoers_file_path(username);
    let output = Command::new("sudo")
        .args(&["-n", "cat", &sudoers_path])
        .output()
        .await;
 
    match output {
        Ok(out) if out.status.success() => {
            let content = String::from_utf8_lossy(&out.stdout);
            // Check for admin markers in the generated sudoers file
            let has_marker = content.contains("# Role: Administrator");
            let has_useradd = content.contains("/usr/sbin/useradd");
            let has_userdel = content.contains("/usr/sbin/userdel");
            // Must have all markers to be considered admin
            has_marker && has_useradd && has_userdel
        }
        _ => false,
    }
}
 
// ── FIX #3: remove_orphaned_sudoers_files — Replace `ls` with read_dir ────────
//
// BEFORE (FRAGILE):
//   Command::new("ls").arg(SUDOERS_DIR)
//   → Output `ls` can have issues with filenames containing newlines.
//   → Not portable, depends on ls output format.
//
// AFTER (ROBUST):
//   tokio::fs::read_dir() — official Rust API, not dependent on shell.
//   Filenames with any characters are handled correctly.
//
pub async fn remove_orphaned_sudoers_files(existing_usernames: &[String]) {
    let read_result = fs::read_dir(SUDOERS_DIR).await;
    let mut entries = match read_result {
        Ok(e) => e,
        Err(e) => {
            eprintln!(
                "{}[ERROR]{} Failed to access directory {}: {}",
                RED, RESET, SUDOERS_DIR, e
            );
            return;
        }
    };
 
    while let Ok(Some(entry)) = entries.next_entry().await {
        // Get filename safely (OsString → str).
        let file_name = match entry.file_name().into_string() {
            Ok(name) => name,
            Err(_) => continue, // skip non-UTF8 filenames
        };
 
        if !file_name.starts_with(SUDOERS_FILE_PREFIX) {
            continue;
        }
 
        let derived_username = file_name
            .trim_start_matches(SUDOERS_FILE_PREFIX)
            .to_string();
 
        // Validate derived username before use.
        if derived_username.is_empty() {
            continue;
        }
 
        if !existing_usernames.contains(&derived_username) {
            println!(
                "{}[PURGING]{} Removing orphaned sudoers file: {}",
                YELLOW, RESET, file_name
            );
            let file_path = format!("{}/{}", SUDOERS_DIR, file_name);
            let _ = Command::new("sudo")
                .args(&["rm", "-f", &file_path])
                .status()
                .await;
        }
    }
}
 
pub async fn clean_orphaned_sudoers(existing_usernames: &[String]) {
    remove_orphaned_sudoers_files(existing_usernames).await;
}
 
#[cfg(test)]
mod tests {
    use super::*;
 
    #[test]
    fn test_build_sudoers_rule_regular_user_contains_lxc_commands() {
        let rule = build_sudoers_rule("alice", &UserRole::Regular);
        assert!(rule.contains("lxc-start"));
        assert!(rule.contains("lxc-attach"));
    }
 
    #[test]
    fn test_build_sudoers_rule_admin_includes_admin_marker() {
        let rule = build_sudoers_rule("bob", &UserRole::Admin);
        assert!(rule.contains("# Role: Administrator"), "Admin rule must contain role marker");
    }
 
    #[test]
    fn test_build_sudoers_rule_regular_excludes_user_management() {
        let rule = build_sudoers_rule("alice", &UserRole::Regular);
        assert!(!rule.contains("useradd"));
        assert!(!rule.contains("userdel"));
        assert!(!rule.contains("passwd"));
        assert!(!rule.contains("# Role: Administrator"), "Regular rule must not contain admin marker");
    }
 
    #[test]
    fn test_build_sudoers_rule_admin_has_all_four_markers() {
        let rule = build_sudoers_rule("bob", &UserRole::Admin);
        assert!(rule.contains("/usr/sbin/useradd *"));
        assert!(rule.contains("/usr/sbin/userdel *"));
        assert!(rule.contains("/usr/bin/passwd *"));
        assert!(rule.contains("# Role: Administrator"));
    }
 
    #[test]
    fn test_build_sudoers_rule_rejects_invalid_username() {
        let rule = build_sudoers_rule("alice; rm -rf /", &UserRole::Admin);
        assert!(rule.is_empty());
    }
 
    #[test]
    fn test_build_sudoers_rule_rejects_username_with_slash() {
        let rule = build_sudoers_rule("../etc/passwd", &UserRole::Regular);
        assert!(rule.is_empty());
    }
 
    #[test]
    fn test_sudoers_file_path_format() {
        assert_eq!(
            sudoers_file_path("frank"),
            "/etc/sudoers.d/melisa_frank"
        );
    }
}