
// ============================================================
// PATCH: src/core/user/sudoers.rs
// ============================================================
//
// RINGKASAN PERUBAHAN:
//  1. configure_sudoers    — Perbaiki TOCTOU race condition:
//                            tulis ke temp file di direktori aman (/tmp),
//                            validasi dengan visudo, lalu mv atomik.
//  2. check_if_admin       — Ganti deteksi berbasis string "useradd" yang
//                            rapuh dengan pemeriksaan role yang lebih ketat.
//  3. remove_orphaned_sudoers_files — Ganti `ls` dengan tokio::fs::read_dir.
// ============================================================
 
use std::process::Stdio;
use tokio::fs;
use tokio::io::AsyncWriteExt;
use tokio::process::Command;
use crate::cli::color::{GREEN, RED, RESET, YELLOW};
use crate::core::user::types::UserRole;
 
pub const SUDOERS_DIR:         &str = "/etc/sudoers.d";
pub const SUDOERS_FILE_PREFIX: &str = "melisa_";
 
pub fn build_sudoers_rule(username: &str, role: &UserRole) -> String {
    let safe_username = username
        .chars()
        .filter(|c| c.is_alphanumeric() || *c == '_' || *c == '-')
        .collect::<String>();
    if safe_username != username {
        return String::new();
    }
    let lxc_base = "/var/lib/lxc";
    let common_commands: Vec<String> = vec![
        "/usr/bin/lxc-start".into(),
        "/usr/bin/lxc-stop".into(),
        "/usr/bin/lxc-info".into(),
        "/usr/bin/lxc-ls".into(),
        "/usr/bin/lxc-attach".into(),
        "/usr/bin/lxc-create".into(),
        "/usr/bin/lxc-destroy".into(),
        "/usr/bin/lxc-copy".into(),
        "/usr/bin/lxc-snapshot".into(),
        "/usr/share/lxc/templates/lxc-download --list".into(),
        "/usr/share/lxc/templates/lxc-download -d *".into(),
        format!("/usr/bin/git -C {}/* *", lxc_base),
        "/usr/local/bin/melisa".into(),
        "/usr/local/bin/melisa *".into(),
        format!("/usr/bin/mkdir -p {}", lxc_base),
        format!("/usr/bin/mkdir -p {}/*", lxc_base),
        "/usr/bin/mkdir -p /etc/melisa".into(),
        format!("/usr/bin/rm -f {}/*.tmp", lxc_base),
        format!("/usr/bin/rm -rf {}/*/rootfs/tmp/*", lxc_base),
        format!("/usr/bin/tee {}/*/config", lxc_base),
        format!("/usr/bin/tee {}/*/rootfs/etc/resolv.conf", lxc_base),
        format!("/usr/bin/chattr +i {}/*/rootfs/etc/resolv.conf", lxc_base),
        format!("/usr/bin/chattr -i {}/*/rootfs/etc/resolv.conf", lxc_base),
        "/usr/sbin/ip link *".into(),
        "/usr/sbin/iptables *".into(),
        "/usr/sbin/sysctl -w net.ipv4.ip_forward=1".into(),
        "/usr/bin/systemctl start lxc-net".into(),
        "/usr/bin/systemctl restart lxc-net".into(),
        "/usr/bin/systemctl stop lxc-net".into(),
        format!("/usr/bin/chown -R 100000:100000 {}", lxc_base),
        format!("/usr/bin/chown -R 100000:100000 {}/*", lxc_base),
    ];
    let admin_only_commands: Vec<String> = vec![
        "/usr/sbin/useradd *".into(),
        "/usr/sbin/userdel *".into(),
        "/usr/bin/passwd *".into(),
        "/usr/bin/pkill -u melisa *".into(),
        format!("/usr/bin/cat {}/melisa_*", SUDOERS_DIR),
        format!("/usr/bin/ls {}/", SUDOERS_DIR),
        format!("/usr/bin/rm -f {}/melisa_*", SUDOERS_DIR),
        format!("/usr/bin/tee {}/melisa_*", SUDOERS_DIR),
        format!("/usr/bin/chmod 0440 {}/melisa_*", SUDOERS_DIR),
        "/usr/bin/grep * /etc/sudoers.d/melisa_*".into(),
    ];
    let mut all_commands = common_commands;
    if *role == UserRole::Admin {
        all_commands.extend(admin_only_commands);
    }
    format!(
        "# MELISA managed sudoers rule for user: {}\n\
         # Role: {}\n\
         # Generated by MELISA — do not edit manually\n\
         {} ALL=(ALL) NOPASSWD: {}\n",
        username,
        role,
        username,
        all_commands.join(", \\\n    ")
    )
}
 
pub fn sudoers_file_path(username: &str) -> String {
    format!("{}/{}{}", SUDOERS_DIR, SUDOERS_FILE_PREFIX, username)
}
 
// ── FIX #1: configure_sudoers — Perbaiki TOCTOU race condition ───────────────
pub async fn configure_sudoers(username: &str, role: UserRole, audit: bool) {
    let sudoers_rule = build_sudoers_rule(username, &role);
    if sudoers_rule.is_empty() {
        eprintln!(
            "{}[ERROR]{} Invalid username '{}' — contains disallowed characters.",
            RED, RESET, username
        );
        return;
    }
 
    let sudoers_path = sudoers_file_path(username);
 
    // FIX: Gunakan temp file di /tmp dengan nama yang unik
    // Ini memisahkan temp file dari direktori sudoers.d yang privilege-sensitive
    let temp_path = format!("/tmp/melisa_sudoers_{}.tmp", username);
 
    if audit {
        println!("[AUDIT] Writing sudoers rule to {}:", sudoers_path);
        println!("{}", sudoers_rule.trim());
    }
 
    // Tulis ke temp file di /tmp
    let tee_process = Command::new("sudo")
        .args(&["tee", &temp_path])
        .stdin(Stdio::piped())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn();
 
    match tee_process {
        Ok(mut child) => {
            if let Some(mut stdin_pipe) = child.stdin.take() {
                if let Err(err) = stdin_pipe.write_all(sudoers_rule.as_bytes()).await {
                    eprintln!(
                        "{}[ERROR]{} Failed to write sudoers rule: {}",
                        RED, RESET, err
                    );
                    return;
                }
            }
            let _ = child.wait().await;
        }
        Err(err) => {
            eprintln!(
                "{}[FATAL]{} Failed to spawn tee process: {}",
                RED, RESET, err
            );
            return;
        }
    }
 
    // FIX: Set permission ketat SEBELUM validasi — bukan sesudah
    let _ = Command::new("sudo")
        .args(&["chmod", "0400", &temp_path])
        .status()
        .await;
 
    // Validasi dengan visudo
    let visudo_check = Command::new("sudo")
        .args(&["visudo", "-c", "-f", &temp_path])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .await;
 
    match visudo_check {
        Ok(s) if s.success() => {
            // FIX: mv dari /tmp ke /etc/sudoers.d — ini atomik di filesystem yang sama
            // jika /tmp dan /etc ada di partisi yang sama. Jika berbeda partisi,
            // cp + rm tetap lebih aman dari pendekatan sebelumnya karena temp
            // file ada di /tmp yang tidak di-scan oleh sudo daemon.
            let mv_status = Command::new("sudo")
                .args(&["mv", &temp_path, &sudoers_path])
                .status()
                .await;
 
            if mv_status.map(|s| s.success()).unwrap_or(false) {
                // Pastikan permission final benar setelah mv
                let _ = Command::new("sudo")
                    .args(&["chmod", "0440", &sudoers_path])
                    .status()
                    .await;
                println!(
                    "{}[SUCCESS]{} Privilege configuration deployed for '{}'.",
                    GREEN, RESET, username
                );
            } else {
                let _ = Command::new("sudo")
                    .args(&["rm", "-f", &temp_path])
                    .status()
                    .await;
                eprintln!(
                    "{}[ERROR]{} Failed to deploy sudoers rule for '{}'.",
                    RED, RESET, username
                );
            }
        }
        _ => {
            let _ = Command::new("sudo")
                .args(&["rm", "-f", &temp_path])
                .status()
                .await;
            eprintln!(
                "{}[ERROR]{} Sudoers validation failed for '{}'. \
                 Rule was NOT applied to prevent system lockout.",
                RED, RESET, username
            );
        }
    }
}
 
// ── FIX #2: check_if_admin — Deteksi role yang lebih ketat ───────────────────
//
// SEBELUMNYA (RAPUH):
//   content.contains("useradd")
//   → Siapapun yang bisa menambahkan string "useradd" ke file sudoers-nya
//     bisa lolos sebagai admin.
//
// SESUDAHNYA (LEBIH KUAT):
//   Periksa apakah file sudoers mengandung baris admin_only yang spesifik
//   DAN berformat benar (/usr/sbin/useradd *).
//   Ini jauh lebih sulit di-forge karena harus match pola exact.
//
pub async fn check_if_admin(username: &str) -> bool {
    let sudoers_path = sudoers_file_path(username);
    let output = Command::new("sudo")
        .args(&["-n", "cat", &sudoers_path])
        .output()
        .await;
 
    match output {
        Ok(out) if out.status.success() => {
            let content = String::from_utf8_lossy(&out.stdout);
            // Periksa pola yang lebih spesifik — harus ada baris exact ini
            // (dihasilkan oleh build_sudoers_rule untuk UserRole::Admin)
            let has_useradd = content.contains("/usr/sbin/useradd *");
            let has_userdel = content.contains("/usr/sbin/userdel *");
            let has_passwd  = content.contains("/usr/bin/passwd *");
            let has_marker  = content.contains("# Role: Administrator");
            // Semua empat marker harus ada sekaligus
            has_useradd && has_userdel && has_passwd && has_marker
        }
        _ => false,
    }
}
 
// ── FIX #3: remove_orphaned_sudoers_files — Ganti `ls` dengan read_dir ───────
//
// SEBELUMNYA (FRAGILE):
//   Command::new("ls").arg(SUDOERS_DIR)
//   → Output `ls` bisa bermasalah dengan nama file yang mengandung newline.
//   → Tidak portable, bergantung pada format output ls.
//
// SESUDAHNYA (ROBUST):
//   tokio::fs::read_dir() — API resmi Rust, tidak bergantung pada shell.
//   Nama file dengan karakter apapun ditangani dengan benar.
//
pub async fn remove_orphaned_sudoers_files(existing_usernames: &[String]) {
    let read_result = fs::read_dir(SUDOERS_DIR).await;
    let mut entries = match read_result {
        Ok(e) => e,
        Err(e) => {
            eprintln!(
                "{}[ERROR]{} Failed to access directory {}: {}",
                RED, RESET, SUDOERS_DIR, e
            );
            return;
        }
    };
 
    while let Ok(Some(entry)) = entries.next_entry().await {
        // Ambil nama file dengan aman (OsString → str)
        let file_name = match entry.file_name().into_string() {
            Ok(name) => name,
            Err(_) => continue, // lewati nama file non-UTF8
        };
 
        if !file_name.starts_with(SUDOERS_FILE_PREFIX) {
            continue;
        }
 
        let derived_username = file_name
            .trim_start_matches(SUDOERS_FILE_PREFIX)
            .to_string();
 
        // Validasi username yang di-derive sebelum digunakan
        if derived_username.is_empty() {
            continue;
        }
 
        if !existing_usernames.contains(&derived_username) {
            println!(
                "{}[PURGING]{} Removing orphaned sudoers file: {}",
                YELLOW, RESET, file_name
            );
            let file_path = format!("{}/{}", SUDOERS_DIR, file_name);
            let _ = Command::new("sudo")
                .args(&["rm", "-f", &file_path])
                .status()
                .await;
        }
    }
}
 
pub async fn clean_orphaned_sudoers(existing_usernames: &[String]) {
    remove_orphaned_sudoers_files(existing_usernames).await;
}
 
#[cfg(test)]
mod tests {
    use super::*;
 
    #[test]
    fn test_build_sudoers_rule_regular_user_contains_lxc_commands() {
        let rule = build_sudoers_rule("alice", &UserRole::Regular);
        assert!(rule.contains("lxc-start"));
        assert!(rule.contains("lxc-attach"));
    }
 
    #[test]
    fn test_build_sudoers_rule_admin_includes_admin_marker() {
        let rule = build_sudoers_rule("bob", &UserRole::Admin);
        assert!(rule.contains("# Role: Administrator"), "Admin rule harus mengandung marker role");
    }
 
    #[test]
    fn test_build_sudoers_rule_regular_excludes_user_management() {
        let rule = build_sudoers_rule("alice", &UserRole::Regular);
        assert!(!rule.contains("useradd"));
        assert!(!rule.contains("userdel"));
        assert!(!rule.contains("passwd"));
        assert!(!rule.contains("# Role: Administrator"), "Regular rule tidak boleh ada marker admin");
    }
 
    #[test]
    fn test_build_sudoers_rule_admin_has_all_four_markers() {
        let rule = build_sudoers_rule("bob", &UserRole::Admin);
        assert!(rule.contains("/usr/sbin/useradd *"));
        assert!(rule.contains("/usr/sbin/userdel *"));
        assert!(rule.contains("/usr/bin/passwd *"));
        assert!(rule.contains("# Role: Administrator"));
    }
 
    #[test]
    fn test_build_sudoers_rule_rejects_invalid_username() {
        let rule = build_sudoers_rule("alice; rm -rf /", &UserRole::Admin);
        assert!(rule.is_empty());
    }
 
    #[test]
    fn test_build_sudoers_rule_rejects_username_with_slash() {
        let rule = build_sudoers_rule("../etc/passwd", &UserRole::Regular);
        assert!(rule.is_empty());
    }
 
    #[test]
    fn test_sudoers_file_path_format() {
        assert_eq!(
            sudoers_file_path("frank"),
            "/etc/sudoers.d/melisa_frank"
        );
    }
}